// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"DevToolsManage","status":true,"description":"総合開発支援プラグイン","parameters":{"開始時に起動":"true","リロードキー":"F12","最前面に表示キー":"F11","高速化切替キー":"F10","強制戦闘勝利キー":"","強制戦闘敗北キー":"","強制戦闘中断キー":"","スクリプト実行キー":"","フリーズキー":"F10","Ctrl同時押し":"false","Alt同時押し":"false","FPS表示":"OFF","タイトルカット":"false","高速開始":"false","高速スピード":"2","メッセージスキップ無効":"false","モバイル偽装":"false","メニューバー表示":"true","クリックメニュー":"1","JSON形式セーブ":"false","起動時情報出力":"true","最前面で起動":"false","リロード機能を使う":"true","右寄せ座標":"640","挨拶非表示":"false","誕生月":"0","誕生日":"0"}},
{"name":"LL_MenuScreenBaseMV","status":true,"description":"メニュー画面立ち絵設定の共通ベースプラグインです。","parameters":{"menuPictures":"[\"{\\\"actorId\\\":\\\"1\\\",\\\"stateId\\\":\\\"\\\",\\\"switchId\\\":\\\"\\\",\\\"imageName\\\":\\\"立_通常_笑い\\\",\\\"x\\\":\\\"0\\\",\\\"y\\\":\\\"0\\\",\\\"scaleX\\\":\\\"100\\\",\\\"scaleY\\\":\\\"100\\\",\\\"pinchPercentage\\\":\\\"25\\\",\\\"pinchImageName\\\":\\\"\\\"}\"]","onSpbPlugin":"","onSpbPluginEnable":"false"}},
{"name":"HPMPLVInvisible","status":true,"description":"HP・MP・レベルを非表示にできます","parameters":{"isVisibleHP":"0","isVisibleMP":"0","isVisibleLV":"0"}},
{"name":"MNKR_TextCodeHelp","status":true,"description":"文章の入力時に制御文字のコードをコピーしやすくヘルプを表示します。","parameters":{}},
{"name":"FixImageLoading","status":true,"description":"画像ロード時のチラつき防止プラグイン","parameters":{}},
{"name":"MessageWindowHidden","status":true,"description":"メッセージウィンドウ一時消去プラグイン","parameters":{"triggerButton":"[\"右クリック\"]","triggerSwitch":"0","linkPictureNumbers":"[]","linkShowPictureNumbers":"[]","disableLinkSwitchId":"0","disableSwitchId":"0","disableInBattle":"false","disableInChoice":"true","restoreByDecision":"false"}},
{"name":"UTA_MessageSkip","status":true,"description":"特定キーを押す事でメッセージをスキップできるようにします。","parameters":{"Skip Key":"control","Show Trace":"false"}}
];
